<?php

namespace Database\Factories;

use App\Repositories\GeneralUsersRepository;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\ExpertiseTechnology>
 */
class ExpertiseTechnologyFactory extends Factory
{
    private GeneralUsersRepository $generalUser;
    private array $list = [];

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $this->generalUser = app()->make(GeneralUsersRepository::class);

        return [
            'user_id' => $this->generalUser->getRandomUserId()->user_id,
            'name'    => $this->getRandomTechnologyName()
        ];
    }

    private function getRandomTechnologyName(): string
    {
        if($this->list === []){
            $this->list = $this->getTechnologyNames();
        }

        $cnt = count($this->list);
        $take = rand(0, $cnt-1);
        $technology = $this->list[$take];
        unset($this->list[$take]);

        $this->list = [
            ...$this->list
        ];

        return $technology;
    }

    private function getTechnologyNames(): array
    {
        // chatgptから生成
        return array_unique([
            "Python",
            "Java",
            "JavaScript",
            "C#",
            "C++",
            "Ruby",
            "Swift",
            "Kotlin",
            "Go",
            "Rust",
            "PHP",
            "TypeScript",
            "Scala",
            "HTML/CSS",
            "Docker",
            "Kubernetes",
            "Apache Kafka",
            "RabbitMQ",
            "Redis",
            "Elasticsearch",
            "GraphQL",
            "Apache Spark",
            "Node.js",
            "TensorFlow",
            "PyTorch",
            "Apache Hadoop",
            "Nginx",
            "MongoDB",
            "Apache Cassandra",
            "Amazon Web Services (AWS)",
            "Microsoft Azure",
            "Google Cloud Platform (GCP)",
            "IBM Cloud",
            "Alibaba Cloud",
            "Oracle Cloud",
            "DigitalOcean",
            "Heroku",
            "Salesforce",
            "VMware Cloud",
            "Red Hat OpenShift",
            "React",
            "Angular",
            "Vue.js",
            "Spring",
            "Flask",
            "Express.js",
            "Django",
            "Ruby on Rails",
            "ASP.NET",
            "Hibernate",
            "Entity Framework",
            "JPA",
            "LINQ",
            "OpenGL",
            "DirectX",
            "Vulkan",
            "Unity",
            "Unreal Engine",
            "Qt",
            "GTK",
            "Tkinter",
            "WPF",
            "WinForms",
            "Android",
            "iOS",
            "macOS",
            "Windows",
            "Linux",
            "Unix",
            "AWS Lambda",
            "Azure Functions",
            "Google Cloud Functions",
            "Firebase",
            "Firestore",
            "BigQuery",
            "DynamoDB",
            "MySQL",
            "PostgreSQL",
            "SQLite",
            "SQL Server",
            "MariaDB",
            "MongoDB",
            "Couchbase",
            "CouchDB",
            "Realm",
            "Neo4j",
            "Cassandra",
            "RabbitMQ",
            "Kafka",
            "ActiveMQ",
            "Redis",
            "Memcached",
            "Elasticsearch",
            "Solr",
            "Kibana",
            "Logstash",
            "Prometheus",
            "Grafana",
            "Zipkin",
            "Jaeger",
            "Splunk",
            "Nagios",
            "Zabbix",
            "PagerDuty",
            "OpsGenie",
            "Datadog",
            "New Relic",
            "Sentry",
            "LogRocket",
            "Raygun",
            "Bugsnag",
            "Rollbar",
            "Honeycomb",
            "AWS CloudFormation",
            "Terraform",
            "Ansible",
            "Chef",
            "Puppet",
            "Jenkins",
            "CircleCI",
            "Travis CI",
            "GitLab CI/CD",
            "GitHub Actions",
            "Bitbucket Pipelines",
            "Docker Compose",
            "Kubernetes Helm",
            "AWS Elastic Beanstalk",
            "Google App Engine",
            "Azure App Service",
            "Heroku",
            "DigitalOcean App Platform",
            "Nginx",
            "Apache HTTP Server",
            "Microsoft IIS",
            "Caddy",
            "HAProxy",
            "Squid",
            "Varnish",
            "Cloudflare",
            "Akamai",
            "Fastly",
            "Netlify",
            "AWS CloudFront",
            "Google Cloud CDN",
            "Azure CDN",
            "Firebase Hosting",
            "Cloudflare Workers",
            "Vercel",
            "Serverless Framework",
            "AWS Amplify",
            "Firebase Realtime Database",
            "Pusher",
            "Socket.io",
            "SignalR",
            "WebRTC",
            "GraphQL",
            "RESTful API",
            "SOAP",
            "gRPC",
            "Swagger",
            "OpenAPI",
            "RAML",
            "GraphQL Schema Language",
            "JSON Schema",
            "Protocol Buffers",
            "Apache Thrift",
            "gRPC-Web",
            "Postman",
            "Insomnia",
            "Paw",
            "Swagger UI",
            "OpenAPI Generator",
            "API Blueprint",
            "Redoc",
            "OpenAPI",
            "Mocha",
            "Jasmine",
            "Jest",
            "PHPUnit",
            "Cucumber",
            "Selenium",
            "Karma",
            "Protractor",
            "Enzyme",
            "Cypress",
            "Puppeteer",
            "Appium",
            "XCTest",
            "JUnit",
            "TestNG",
            "NUnit",
            "RSpec",
            "Pytest",
            "Robot Framework",
            "Ginkgo",
            "Concourse",
            "Jenkins",
            "Travis CI",
            "CircleCI",
            "GitLab CI",
            "Azure Pipelines",
            "TeamCity",
            "Bamboo",
            "Grafana",
            "Prometheus",
            "Zabbix",
            "Datadog",
            "New Relic",
            "Sentry",
            "ELK Stack",
            "Graylog",
            "Splunk",
            "Nagios",
            "Icinga",
            "AWS CloudWatch",
            "Azure Monitor",
            "Google Cloud Monitoring",
            "Prometheus",
            "Grafana",
            "Datadog",
            "New Relic",
            "Sentry",
            "LogRocket",
            "Raygun",
            "Bugsnag",
            "Rollbar",
            "Honeycomb",
            "Amazon CloudWatch",
            "Google Cloud Monitoring",
            "Azure Monitor",
            "Datadog",
            "New Relic",
            "AppDynamics",
            "Dynatrace",
            "Splunk",
            "Elastic Stack",
            "Sumo Logic",
            "Loggly",
            "Papertrail",
            "LogDNA",
            "Fluentd",
            "Prometheus",
            "Grafana",
            "Jaeger",
            "Zipkin",
            "OpenTracing",
            "AWS X-Ray",
            "Honeycomb",
            "Datadog",
            "Sentry",
            "Raygun",
            "Rollbar",
            "Bugsnag",
            "Google Cloud Trace",
            "Azure Application Insights",
            "New Relic",
            "Dynatrace",
            "AppDynamics",
            "AWS CodeDeploy",
            "Google Cloud Deployment Manager",
            "Azure Resource Manager",
            "AWS CodePipeline",
            "Google Cloud Build",
            "Azure Pipelines",
            "Jenkins",
            "Bamboo",
            "TeamCity",
            "CircleCI",
            "Travis CI",
            "GitLab CI",
            "AWS CodeCommit",
            "GitHub",
            "GitLab",
            "Bitbucket",
            "AWS CodeBuild",
            "Google Cloud Build",
            "Azure Pipelines",
            "Jenkins",
            "CircleCI",
            "Travis CI",
            "GitLab CI",
            "Team"
        ]);
    }
}
