# ワークフロー名(任意)
name: learning-dispatch-system-ci-workflow

# 当該ワークフローのトリガーを指定(実行タイミング)
on: 
  push: 
    branches:
      - master
  pull_request: 
    branches: 
      - master

# 仮想マシン内で実行されるタスク定義
jobs: 
  learning-dispatch-system-ci: 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./project/learning_dispatch_system
    services:
      mysql:
        image: mysql:8.0-debian
        env: 
          MYSQL_DATABASE: test_learning_storage
          MYSQL_ROOT_PASSWORD: rootpass
        volumes:
          - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
        ports: 
          - '3306:3306'
    steps: 
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          path: './project/learning_dispatch_system'
          submodules: 'recursive'
          
      - name: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: npm

      - name: copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: key generate
        run: php artisan key:generate

      - name: composer install
        run: composer install --no-progress

      - name: npm install
        run: npm i

      - name: npm build
        run: npm run build

      - name: migrate
        run: php artisan migrate

      - name: phpstan run
        run: ./vendor/bin/phpstan analyse --memory-limit=512M

      - name: test run
        run: php artisan test








